# Generated by Django 3.1 on 2020-08-21 04:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='introduce',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='topic',
        ),
        migrations.RemoveField(
            model_name='post',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
