# Generated by Django 3.1 on 2020-08-22 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_auto_20200822_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='introduce',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.TextField(max_length=300),
        ),
    ]
