# Generated by Django 3.1 on 2020-08-21 11:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField()),
                ('how_much', models.DecimalField(decimal_places=2, max_digits=6)),
                ('job_detail', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('contact', models.TextField()),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
