# Generated by Django 3.1 on 2020-08-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_job', '0005_auto_20200821_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.TextField(),
        ),
    ]
