# Generated by Django 3.1 on 2020-08-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_job', '0006_auto_20200821_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='contact',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_detail',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='job',
            name='subject',
            field=models.CharField(max_length=15),
        ),
    ]
