# Generated by Django 3.1 on 2020-08-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money_job', '0007_auto_20200822_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
